[project]
name = "nlp-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets",
    "fsspec>=2026.1.0",
    "huggingface-hub<1.16.0",
    "nltk>=3.9.2",
    "numpy<2.0",
    "pandas>=2.3.3",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "sentence-transformers==2.2.2",
    "transformers==4.34.0",
    "accelerate==0.21.0",
    "torch>=2.0.0",
    "spacy>=3.8.11",
    "wordcloud>=1.9.5",
]
